title: Quit Social Media
email: hi@quitsocialmedia.club
description: >- # this means to ignore newlines until "baseurl:"
    Why and how to quit Social Media.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quitsocialmedia.club" # the base hostname & protocol for your site, e.g. http://example.com
author: Tommi
publisher: Tommi
twitter_username: xplosionmind
github_username: xplosionmind
git_repository: "quitsocialmedia.club"
future: true
profile: true
livereload: true
strict_front_matter: true
favicon: "/favicon.svg"
image: "/logos/qsm.png"
images: "/images"
assets: "/assets"
video: "/video"
audio: "/audio"
logos: "/logos"
fonts: "https://tommi.space/fonts"
exclude:
  - riordinare/
keep_files:
  - images/
  - assets/

social:
  name: xplosionmind
tagline: "Living a healthier life on the web"
twitter:
  username: xplosionmind
  card: summary

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-target-blank
  - jekyll-watch
  - jekyll-redirect-from
  - jekyll-debug
  - jekyll-watch
  - jekyll-email-protect

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: all

permalink: /:title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      lang: "en"
      image: "/logos/qsm.png"
      toc: true
      anchors: true
